# Generated by Django 3.0.3 on 2020-02-14 17:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('line', django.contrib.gis.db.models.fields.LineStringField(dim=3, srid=4326)),
                ('mmsi', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
