# Generated by Django 3.0.3 on 2020-02-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='mmsi',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
