# Generated by Django 3.0.3 on 2020-02-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_auto_20200214_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='line',
            new_name='geojson',
        ),
    ]
