# Generated by Django 3.0.3 on 2020-02-17 10:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0003_auto_20200215_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('geojson', django.contrib.gis.db.models.fields.LineStringField(dim=3, srid=4326)),
                ('trainNumber', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
