# Generated by Django 3.0.3 on 2020-02-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0004_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='draught',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='shipType',
            field=models.IntegerField(null=True),
        ),
    ]
