# Generated by Django 3.0.3 on 2020-02-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0005_auto_20200224_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
