# Generated by Django 3.0.3 on 2020-02-25 08:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0007_train_traincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='speed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0], size=None),
            preserve_default=False,
        ),
    ]
