# Generated by Django 3.0.4 on 2020-05-05 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0011_auto_20200408_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datahub.Vessel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datahub.Train')),
            ],
        ),
    ]
