# Generated by Django 3.0.4 on 2020-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0014_map_statistics_reverse_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsFile',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('colorHex', models.CharField(default='#1FBAD6', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('is_reverse', models.BooleanField(default=False)),
                ('reverse_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='map',
            name='statistics_reverse_urls',
        ),
        migrations.AddField(
            model_name='map',
            name='statistics',
            field=models.ManyToManyField(blank=True, null=True, to='datahub.StatisticsFile'),
        ),
    ]
